name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python installation
        run: |
          python --version
          pip --version

      - name: Check Python syntax
        run: |
          python -m py_compile server.py
          python -m py_compile app/app.py

      - name: Validate Flask application structure
        run: |
          python -c "import server; print('Server module loaded successfully')"
          python -c "from app import app; print('Flask app imported successfully')"

      - name: Build status
        run: echo "Build completed successfully!"
